//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormulaBasketball.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FormulaBasketball.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dtersauuw Sagua 0.68
        ///Blaist Blaland  8.34    use Blaland
        ///Red Rainbow     0.50    use Blaland
        ///Bielosia        4.82    use Loviniosa
        ///Lyintaria       3.83    use Loviniosa
        ///Pyxanovia       2.78    use Loviniosa
        ///Holy Yektonisa  1.00    use Loviniosa
        ///Czalliso        1.35
        ///Holykol 0.12    use Czalliso
        ///Norkute 0.05    use Czalliso
        ///Darvincia       1.89
        ///Sagua   3.38
        ///Height Sagua    1.90    use Sagua
        ///Key to Don      1.90    use Sagua
        ///Nausicaa        1.20    use Sagua
        ///Nausicaa        0.70    use Darvincia [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string config {
            get {
                return ResourceManager.GetString("config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serkr	Piri	Atona
        ///Serkr	Nouka	Lereŋ
        ///Serkr	Olue	Pitwa
        ///Serkr	Tise	Epi
        ///Serkr	Lekena	Porewo
        ///Serkr	Paekua	Tuni
        ///Serkr	Oevu	Lome
        ///Serkr	Apu	Aq&apos;aie
        ///Dtersauuw Sagua	P&apos;uyo	Lek&apos;at
        ///Dtersauuw Sagua	Tsekon	Unup&apos;a
        ///Dtersauuw Sagua	Litsaw	T&apos;es&apos;vak
        ///Dtersauuw Sagua	Ivek&apos;il	Wap&apos;t&apos;ebw
        ///Solea	pihten	lekeŋ
        ///Solea	vaŋun	peval
        ///Solea	uqeth	nešik
        ///Solea	ikánag	pátélokain
        ///Solea	pekleɰ	tiwan
        ///Solea	tikit&apos;	kutap
        ///Solea	napuk	zeinélak&apos;
        ///Solea	šunokiɰev	pavútekaš
        ///Solea	kéhi	guqavpel
        ///Solea	kal	aiqík
        ///Solea	lagak	qivektuketuk
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string names {
            get {
                return ResourceManager.GetString("names", resourceCulture);
            }
        }
    }
}
